mqtt:
  client-id: springboot_paho_${random.value}

odds:
  win:
    fixed-rate: 500
    topic: public/odds/20211001ST/ra/0/win/

  pla:
    fixed-rate: 350
    topic: public/odds/20211001ST/ra/0/pla/    

odds-all:
  win:
    init-delay: 0
    fixed-rate: 8000

  pla:
    init-delay: 4000
    fixed-rate: 8000
    
odds-hist:
  win:
    #1st set WIN
    - '0': 6.6
      '1': 99
      '2': 15
      '3': 9
      '4': 1.4
      '5': 31
      '6': 99
      '7': 99
      '8': 11
      '9': 28
      '10': 99
    #2nd set WIN
    - '0': 6.5
      '1': 99
      '2': 14
      '3': 9.3
      '4': 1.4
      '5': 35
      '6': 99
      '7': 99
      '8': 12
      '9': 32
      '10': 99
    #3rd set WIN
    - '0': 5.8
      '1': 93
      '2': 13
      '3': 8.9
      '4': 1.5
      '5': 30
      '6': 88
      '7': 99
      '8': 10
      '9': 29
      '10': 99
    #4th set WIN  
    - '0': 5.6
      '1': 87
      '2': 12
      '3': 9.1
      '4': 1.5
      '5': 28
      '6': 83
      '7': 99
      '8': 10
      '9': 27
      '10': 99
  pla:
    #1st set PLA
    - '0': 1.4
      '1': 15
      '2': 2.4
      '3': 1.7
      '4': 1.1
      '5': 6.2
      '6': 14
      '7': 22
      '8': 2.4
      '9': 4
      '10': 15
    #2nd set PLA
    - '0': 1.5
      '1': 14
      '2': 2.3
      '3': 1.7
      '4': 1
      '5': 6.5
      '6': 13
      '7': 21
      '8': 2.5
      '9': 4.8
      '10': 14
    #3rd set PLA
    - '0': 1.5
      '1': 11
      '2': 2.5
      '3': 1.8
      '4': 1.1
      '5': 5.6
      '6': 11
      '7': 17
      '8': 2.6
      '9': 4.3
      '10': 12              
    #4th set PLA
    - '0': 1.5
      '1': 10
      '2': 2.4
      '3': 1.8
      '4': 1.2
      '5': 5.1
      '6': 10
      '7': 16
      '8': 2.5
      '9': 4.3
      '10': 11  

---
spring:
  config:
    activate:
      on-profile:
      - local-hivemq
    
mqtt:
#  client-id: springboot_paho_${random.value}
  broker-url: tcp://localhost:1883
  username: user1
  password: hm93bqCj6xR562U

---
spring:
  config:
    activate:
      on-profile:
      - local-k8s-hivemq
    
mqtt:
#  client-id: springboot_paho_${random.value}
  broker-url: tcp://192.168.142.71:1883
  username: user1
  password: hm93bqCj6xR562U
  
---
spring:
  config:
    activate:
      on-profile:
      - local-solace
    
mqtt:
#  client-id: springboot_paho_${random.value}
  broker-url: tcp://localhost:1883
  username: admin
  password: admin
 
---
spring:
  config:
    activate:
      on-profile:
      - my-solace-cloud-trial
    
mqtt:
#  client-id: springboot_paho_${random.value}
  broker-url: wss://mrnzmkh0ufgnb.messaging.solace.cloud:8443
  username: solace-cloud-client
  password: e6r6a8ufj56v9dimfp6tgdectt
  
---
spring:
  config:
    activate:
      on-profile:
      - ext-solace
    
mqtt:
#  client-id: springboot_paho_${random.value}
  broker-url: ws://118.143.15.74:51884/mqtt
  username: tempuser
  password: "00000000"